config/routes.rb
Rails.application.routes.draw do

  resources :ads
  root 'ads#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  before_filter :check_logged_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  
  def index
    @ads = Ad.all
  end
  
  def show
  end

  def new
    @ad = Ad.new
  end

  def edit
  end

  def create
    @ad = Ad.new(ad_params)
    if @ad.save
      redirect_to ad_path(@ad.id)
    else
      render :new
    end
  end

  def update
    if @ad.update(ad_params)
      redirect_to ad_path(@ad.id)
    else
      render :edit
    end
  end

  def destroy
    if @ad.destroy
      redirect_to ads_path
    end
  end

  private

  def set_ad
    @ad = Ad.find(params[:id])
  end

  def ad_params
    params.require(:ad).permit(:name, :description, :price, :seller_id, :email, :img_url)
  end

  def check_logged_in
    authenticate_or_request_with_http_basic("Ads") do |username, password|
      username == "admin" && password == "bjifilm_001"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
  <p>
    <b>Name</b><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <b>Description</b><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <b>Price</b><br/>
    <%= f.text_field :price %>
  </p>
  <p>
    <b>Seller</b><br/>
    <%= f.text_field :seller_id %>
  </p>
  <p>
    <b>Email</b><br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <b>Img url</b><br/>
    <%= f.text_field :img_url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/ads/edit.html.erb
<h1>Edit <%= @ad.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', ad_path(@ad.id) %>

app/views/ads/index.html.erb
<h1>All Ads</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ads.each do |ad| %>
      <tr>
	<% @name=ad.name %>
	<td><%= link_to @name, ad %></td>
	<td><%= ad.description %></td>
	<td><%= ad.price.to_i %></td>
	<td><%= link_to 'Delete', ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad', new_ad_path %>

app/views/ads/new.html.erb
<h1>New Ad</h1>

<%= render 'form' %>

app/views/ads/show.html.erb
<p>
  <b>Name:</b><%= @ad.name %>
</p>

<p>
  <b>Description:</b><%= @ad.description %>
</p>

<p>
  <b>Price:</b><%= @ad.price %>
</p>

<p>
  <b>Seller Id:</b><%= @ad.seller_id %>
</p>

<p>
  <b>Email:</b><%= @ad.email %>
</p>

<p>
  <img src="<%= @ad.img_url %>"/>
</p>

<br>

<%= link_to 'Back', ads_path %>||<%= link_to 'Edit', edit_ad_path(@ad.id) %>

app/views/layouts/ads.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Ads: <%= controller.action_name %></title>
    <%= stylesheet_link_tag 'default.css' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <div id="wrapper">
      <div id="header">
	<div>
	  <h1>MeBay</h1>
	  <ul id="nav">
	    <li><%= link_to 'All Ads', ads_path %></li>
	  </ul>
	</div>
      </div>
      <div id="content">
	<%= yield %>
      </div>
      <div id="clearfooter"></div>
    </div>
    <div id="footer"></div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ads</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>